version: "3"

tasks:
  start-dev:
    deps:
      - css-watch
      - air

  air:
    env:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_NAME: "todo_db"
    cmds:
      - air

  css-watch:
    desc: "tailwind watch build"
    cmds:
      - ./tailwindcss -i css/input.css -o css/output.css --watch

  css-minify:
    desc: "tailwind watch build"
    cmds:
      - ./tailwindcss -i css/input.css -o css/output.css --minify

  build-prod:
    desc: "build the prod applicaiton"
    cmds:
      - docker compose build
  start-prod:
    desc: "start the prod applicaiton"
    cmds:
      - docker compose up
  start-prod-bg:
    desc: "start the prod applicaiton in the background"
    cmds:
      - docker compose up -d
  stop-prod:
    desc: "stop the prod applicaiton"
    cmds:
      - docker compose down
  update-prod:
    desc: "run the pipeline to rebuild prod"
    cmds:
      - task stop-prod
      - task build-prod
      - task start-prod-bg
